package goyze_test

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"

	errs "github.com/gomatic/go-error"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/analysis"

	goyze "github.com/gomatic/go-yze"
)

func fakeDriver(fset *token.FileSet, results []goyze.DriverResult, err error) goyze.Driver {
	return func(_ []goyze.Registration, _ []goyze.Pattern) (*token.FileSet, []goyze.DriverResult, error) {
		return fset, results, err
	}
}

func TestRunCollectsDiagnosticsFromAllResults(t *testing.T) {
	fset, f := newFile(t)
	results := []goyze.DriverResult{
		{Registration: sampleRegistration(), Diagnostics: []analysis.Diagnostic{{Pos: f.Pos(0), Message: "boom"}}},
		{Registration: sampleRegistration(), Diagnostics: nil},
	}

	report, err := goyze.Run(
		fakeDriver(fset, results, nil),
		[]goyze.Registration{sampleRegistration()},
		[]goyze.Pattern{"./..."},
	)

	require.NoError(t, err)
	require.Len(t, report.Diagnostics, 1)
	assert.Equal(t, "yze/errconst", report.Diagnostics[0].Rule)
	assert.Equal(t, "boom", report.Diagnostics[0].Message)
}

func TestRunValidatesRegistrationsBeforeDriving(t *testing.T) {
	bad := sampleRegistration()
	bad.Name = ""
	called := false
	driver := func(_ []goyze.Registration, _ []goyze.Pattern) (*token.FileSet, []goyze.DriverResult, error) {
		called = true
		return nil, nil, nil
	}

	_, err := goyze.Run(driver, []goyze.Registration{bad}, nil)

	require.ErrorIs(t, err, goyze.ErrMissingName)
	assert.False(t, called, "driver must not run when a registration is invalid")
}

func TestRunWrapsDriverFailure(t *testing.T) {
	boom := errs.Const("kaboom")

	_, err := goyze.Run(fakeDriver(nil, nil, boom), []goyze.Registration{sampleRegistration()}, nil)

	require.ErrorIs(t, err, goyze.ErrDriver)
	require.ErrorIs(t, err, boom)
}

func TestRunDropsDiagnosticsInGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "gen.pb.go")
	src := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n"
	require.NoError(t, os.WriteFile(path, []byte(src), 0o644))
	fset := token.NewFileSet()
	f := fset.AddFile(path, fset.Base(), len(src))
	f.SetLinesForContent([]byte(src))

	results := []goyze.DriverResult{
		{
			Registration: sampleRegistration(),
			Diagnostics:  []analysis.Diagnostic{{Pos: f.Pos(0), Message: "in generated"}},
		},
	}
	report, err := goyze.Run(
		fakeDriver(fset, results, nil),
		[]goyze.Registration{sampleRegistration()},
		[]goyze.Pattern{"./..."},
	)
	require.NoError(t, err)
	assert.Empty(t, report.Diagnostics, "generated-file findings are dropped")
}
