package goyze_test

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"

	errs "github.com/gomatic/go-error"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/analysis"

	goyze "github.com/gomatic/go-yze"
)

func fakeDriver(fset *token.FileSet, results []goyze.DriverResult, err error) goyze.Driver {
	return func(_ []goyze.Registration, _ []goyze.Pattern) (*token.FileSet, []goyze.DriverResult, error) {
		return fset, results, err
	}
}

func TestRunCollectsDiagnosticsFromAllResults(t *testing.T) {
	fset, f := newFile(t)
	results := []goyze.DriverResult{
		{Registration: sampleRegistration(), Diagnostics: []analysis.Diagnostic{{Pos: f.Pos(0), Message: "boom"}}},
		{Registration: sampleRegistration(), Diagnostics: nil},
	}

	report, err := goyze.Run(
		fakeDriver(fset, results, nil),
		[]goyze.Registration{sampleRegistration()},
		[]goyze.Pattern{"./..."},
	)

	require.NoError(t, err)
	require.Len(t, report.Diagnostics, 1)
	assert.Equal(t, "yze/errconst", report.Diagnostics[0].Rule)
	assert.Equal(t, "boom", report.Diagnostics[0].Message)
}

func TestRunValidatesRegistrationsBeforeDriving(t *testing.T) {
	bad := sampleRegistration()
	bad.Name = ""
	called := false
	driver := func(_ []goyze.Registration, _ []goyze.Pattern) (*token.FileSet, []goyze.DriverResult, error) {
		called = true
		return nil, nil, nil
	}

	_, err := goyze.Run(driver, []goyze.Registration{bad}, nil)

	require.ErrorIs(t, err, goyze.ErrMissingName)
	assert.False(t, called, "driver must not run when a registration is invalid")
}

func TestRunWrapsDriverFailure(t *testing.T) {
	boom := errs.Const("kaboom")

	_, err := goyze.Run(fakeDriver(nil, nil, boom), []goyze.Registration{sampleRegistration()}, nil)

	require.ErrorIs(t, err, goyze.ErrDriver)
	require.ErrorIs(t, err, boom)
}

func TestRunDropsDiagnosticsInGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "gen.pb.go")
	src := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n"
	require.NoError(t, os.WriteFile(path, []byte(src), 0o644))
	fset := token.NewFileSet()
	f := fset.AddFile(path, fset.Base(), len(src))
	f.SetLinesForContent([]byte(src))

	results := []goyze.DriverResult{
		{
			Registration: sampleRegistration(),
			Diagnostics:  []analysis.Diagnostic{{Pos: f.Pos(0), Message: "in generated"}},
		},
	}
	report, err := goyze.Run(
		fakeDriver(fset, results, nil),
		[]goyze.Registration{sampleRegistration()},
		[]goyze.Pattern{"./..."},
	)
	require.NoError(t, err)
	assert.Empty(t, report.Diagnostics, "generated-file findings are dropped")
}

// TestSourceOnlyScopeDropsTestFileFindings pins the test-file policy: a rule
// about production design reports in source and stays silent in _test.go, while
// an unscoped rule reports in both.
func TestSourceOnlyScopeDropsTestFileFindings(t *testing.T) {
	t.Parallel()

	fset := token.NewFileSet()
	source := fset.AddFile("/pkg/thing.go", -1, 100).Pos(0)
	test := fset.AddFile("/pkg/thing_test.go", -1, 100).Pos(0)
	reported := []analysis.Diagnostic{{Pos: source, Message: "in source"}, {Pos: test, Message: "in test"}}

	scoped := goyze.Registration{Name: "shape", Analyzer: &analysis.Analyzer{Name: "shape"}}.
		WithTestScope(goyze.TestScopeSourceOnly)
	unscoped := goyze.Registration{Name: "any", Analyzer: &analysis.Analyzer{Name: "any"}}
	driver := func([]goyze.Registration, []goyze.Pattern) (*token.FileSet, []goyze.DriverResult, error) {
		return fset, []goyze.DriverResult{
			{Registration: scoped, Diagnostics: reported},
			{Registration: unscoped, Diagnostics: reported},
		}, nil
	}

	report, err := goyze.Run(driver, []goyze.Registration{scoped, unscoped}, []goyze.Pattern{"."})

	require.NoError(t, err)
	byRule := map[string][]string{}
	for _, d := range report.Diagnostics {
		byRule[d.Rule] = append(byRule[d.Rule], d.Path)
	}
	assert.Equal(t, []string{"/pkg/thing.go"}, byRule["yze/shape"], "source-only drops the test-file finding")
	assert.Equal(
		t,
		[]string{"/pkg/thing.go", "/pkg/thing_test.go"},
		byRule["yze/any"],
		"an unscoped rule reports in both",
	)
}

// TestKeyOfCollapsesTheDuplicateTheTestVariantLoadProduces names keyOf's and
// diagnosticKey's claim. Because the loader presents a package's non-test files
// in both the plain package and its test variant (see defaultLoad), an analyzer
// reporting on those files fires once per variant — so without this projection
// every such finding is printed twice, and a reviewer counting findings sees
// double the real number.
//
// The projection must be on rule+path+line+col+message together: collapsing on
// anything coarser would swallow a genuinely distinct second finding on the
// same line, which is the failure that would make the deduplication itself a
// bug.
func TestDiagnosticKeyOfCollapsesTheDuplicateTheTestVariantLoadProduces(t *testing.T) {
	t.Parallel()
	want, must := assert.New(t), require.New(t)

	fset, f := newFile(t)
	// Three findings on one file: two share a line and differ only in column,
	// two share a position and differ only in message. Emitting the SAME slice
	// from two driver results reproduces exactly what the test-variant load
	// does — the identical finding arriving twice.
	found := []analysis.Diagnostic{
		{Pos: f.Pos(0), Message: "boom"},
		{Pos: f.Pos(5), Message: "boom"},
		{Pos: f.Pos(0), Message: "different finding"},
	}
	results := []goyze.DriverResult{
		{Registration: sampleRegistration(), Diagnostics: found},
		{Registration: sampleRegistration(), Diagnostics: found},
	}

	report, err := goyze.Run(
		fakeDriver(fset, results, nil),
		[]goyze.Registration{sampleRegistration()},
		[]goyze.Pattern{"./..."},
	)

	must.NoError(err)
	want.Len(report.Diagnostics, 3,
		"the identical finding collapses across variants; a different column or message does not")
}
