package goyze

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/iotest"

	errs "github.com/gomatic/go-error"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const errBoom errs.Const = "boom"

func newGenerated(read readHead) generatedFiles {
	return generatedFiles{read: read, seen: map[filePath]bool{}}
}

func TestIsGeneratedDetectsTheMarker(t *testing.T) {
	g := newGenerated(func(filePath) ([]byte, error) {
		return []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n"), nil
	})
	assert.True(t, g.isGenerated("x.pb.go"))
	assert.True(t, g.isGenerated("x.pb.go"), "memoized verdict")
}

func TestIsGeneratedStopsAtPackageClause(t *testing.T) {
	g := newGenerated(func(filePath) ([]byte, error) {
		return []byte("package a\n\n// Code generated by hand. DO NOT EDIT.\n"), nil
	})
	assert.False(t, g.isGenerated("a.go"), "marker after the package clause does not count")
}

func TestIsGeneratedRequiresTheWholeLineShape(t *testing.T) {
	g := newGenerated(func(filePath) ([]byte, error) {
		return []byte("// This file was Code generated sort of. DO NOT EDIT maybe.\npackage a\n"), nil
	})
	assert.False(t, g.isGenerated("a.go"))
}

func TestIsGeneratedUnreadableFileSurvives(t *testing.T) {
	g := newGenerated(func(filePath) ([]byte, error) { return nil, errBoom })
	assert.False(t, g.isGenerated("gone.go"), "unreadable files keep their diagnostics")
}

func TestOSReadHeadReadsAndErrors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "f.go")
	require.NoError(t, os.WriteFile(path, []byte("// Code generated by x. DO NOT EDIT.\npackage f\n"), 0o644))
	head, err := osReadHead(filePath(path))
	require.NoError(t, err)
	assert.Contains(t, string(head), "DO NOT EDIT")

	empty := filepath.Join(dir, "empty.go")
	require.NoError(t, os.WriteFile(empty, nil, 0o644))
	head, err = osReadHead(filePath(empty))
	require.NoError(t, err, "an empty file is an empty preamble, not a failure")
	assert.Empty(t, head)

	_, err = osReadHead(filePath(filepath.Join(dir, "absent.go")))
	assert.Error(t, err)
}

func TestOSReadHeadScansTheWholePreamble(t *testing.T) {
	// A license preamble longer than any fixed head size must not hide the
	// marker: like ast.IsGenerated, every comment line before the package
	// clause counts.
	preamble := strings.Repeat("// license line padding the preamble\r\n", 200)
	content := preamble + "// Code generated by x. DO NOT EDIT.\r\npackage f\r\n\r\nfunc F() {}\r\n"
	require.Greater(t, len(preamble), 4096, "the preamble must exceed the old fixed head")
	path := filepath.Join(t.TempDir(), "long.go")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	g := newGenerated(osReadHead)

	assert.True(t, g.isGenerated(filePath(path)), "a marker after a long license preamble still counts")
}

func TestOSReadHeadStopsAtThePackageClause(t *testing.T) {
	path := filepath.Join(t.TempDir(), "p.go")
	require.NoError(t, os.WriteFile(path, []byte("// hi\npackage f\n\nfunc F() {}\n"), 0o644))

	head, err := osReadHead(filePath(path))

	require.NoError(t, err)
	assert.Equal(t, "// hi\npackage f\n", string(head), "the marker cannot appear past the package clause")
}

func TestReadThroughPackageClauseReadsToEOFWithoutPackageClause(t *testing.T) {
	head, err := readThroughPackageClause(strings.NewReader("// a\n// b"))

	require.NoError(t, err)
	assert.Equal(t, "// a\n// b", string(head), "a final unterminated line is still part of the preamble")
}

func TestReadThroughPackageClauseReportsReadErrors(t *testing.T) {
	_, err := readThroughPackageClause(iotest.ErrReader(errBoom))

	require.ErrorIs(t, err, errBoom)
}

func TestIsGeneratedHeadWithoutMarkerOrPackage(t *testing.T) {
	g := newGenerated(func(filePath) ([]byte, error) {
		return []byte("// just a build-tag header\n//go:build linux\n"), nil
	})
	assert.False(t, g.isGenerated("h.go"))
}
