package goyze

import (
	"os"
	"path/filepath"
	"testing"

	errs "github.com/gomatic/go-error"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const errBoom errs.Const = "boom"

func newGenerated(read readHead) generatedFiles {
	return generatedFiles{read: read, seen: map[string]bool{}}
}

func TestIsGeneratedDetectsTheMarker(t *testing.T) {
	g := newGenerated(func(string) ([]byte, error) {
		return []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n"), nil
	})
	assert.True(t, g.isGenerated("x.pb.go"))
	assert.True(t, g.isGenerated("x.pb.go"), "memoized verdict")
}

func TestIsGeneratedStopsAtPackageClause(t *testing.T) {
	g := newGenerated(func(string) ([]byte, error) {
		return []byte("package a\n\n// Code generated by hand. DO NOT EDIT.\n"), nil
	})
	assert.False(t, g.isGenerated("a.go"), "marker after the package clause does not count")
}

func TestIsGeneratedRequiresTheWholeLineShape(t *testing.T) {
	g := newGenerated(func(string) ([]byte, error) {
		return []byte("// This file was Code generated sort of. DO NOT EDIT maybe.\npackage a\n"), nil
	})
	assert.False(t, g.isGenerated("a.go"))
}

func TestIsGeneratedUnreadableFileSurvives(t *testing.T) {
	g := newGenerated(func(string) ([]byte, error) { return nil, errBoom })
	assert.False(t, g.isGenerated("gone.go"), "unreadable files keep their diagnostics")
}

func TestOSReadHeadReadsAndErrors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "f.go")
	require.NoError(t, os.WriteFile(path, []byte("// Code generated by x. DO NOT EDIT.\npackage f\n"), 0o644))
	head, err := osReadHead(path)
	require.NoError(t, err)
	assert.Contains(t, string(head), "DO NOT EDIT")

	empty := filepath.Join(dir, "empty.go")
	require.NoError(t, os.WriteFile(empty, nil, 0o644))
	_, err = osReadHead(empty)
	assert.Error(t, err, "an empty file reads as EOF")

	_, err = osReadHead(filepath.Join(dir, "absent.go"))
	assert.Error(t, err)
}

func TestIsGeneratedHeadWithoutMarkerOrPackage(t *testing.T) {
	g := newGenerated(func(string) ([]byte, error) {
		return []byte("// just a build-tag header\n//go:build linux\n"), nil
	})
	assert.False(t, g.isGenerated("h.go"))
}
